services:
  app:
    build:
      context: .
      target: production
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - POSTGRES_URL=jdbc:postgresql://postgres/filmdb
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_DB=filmdb
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "filmdb" ]
      interval: 5s
      timeout: 2s
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
