DROP TABLE film IF EXISTS;
DROP TABLE person IF EXISTS;
DROP TABLE role IF EXISTS;
DROP TABLE film_person_directed IF EXISTS;

CREATE TABLE film(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    release_date DATE NOT NULL,
    synopsis CHARACTER VARYING(255),
    title CHARACTER VARYING(255) NOT NULL
);

CREATE TABLE person(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    dob DATE,
    name CHARACTER VARYING(255) NOT NULL
);

CREATE TABLE film_person_directed(
    film_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL
);

CREATE TABLE role(
    film_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    "CHARACTER" CHARACTER VARYING(255) NOT NULL
);

ALTER TABLE film_person_directed ADD CONSTRAINT pk_directed PRIMARY KEY(film_id, person_id);
ALTER TABLE film_person_directed ADD CONSTRAINT fk_directed_film FOREIGN KEY(film_id) REFERENCES film (id);
ALTER TABLE film_person_directed ADD CONSTRAINT fk_directed_person FOREIGN KEY(person_id) REFERENCES person (id);

ALTER TABLE role ADD CONSTRAINT pk_role PRIMARY KEY(film_id, person_id);
ALTER TABLE role ADD CONSTRAINT fk_role_film FOREIGN KEY(film_id) REFERENCES film (id);
ALTER TABLE role ADD CONSTRAINT fk_role_person FOREIGN KEY(person_id) REFERENCES person (id);