CREATE TABLE film (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    release_date date NOT NULL,
    synopsis character varying(255),
    title character varying(255) NOT NULL
);

CREATE TABLE person (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    date_of_birth date,
    name character varying(255) NOT NULL
);

CREATE TABLE film_person_directed (
    film_id bigint NOT NULL,
    person_id bigint NOT NULL,
    PRIMARY KEY(film_id, person_id)
);

ALTER TABLE ONLY film_person_directed
    ADD CONSTRAINT fk_directed_on_film FOREIGN KEY (film_id) REFERENCES film(id);

ALTER TABLE ONLY film_person_directed
    ADD CONSTRAINT fk_directed_on_person FOREIGN KEY (person_id) REFERENCES person(id);

CREATE TABLE role (
    film_id bigint NOT NULL,
    person_id bigint NOT NULL,
    "character" character varying(255) NOT NULL,
    PRIMARY KEY(film_id, person_id)
);

ALTER TABLE ONLY role
    ADD CONSTRAINT fk_role_on_film FOREIGN KEY (film_id) REFERENCES film(id);

ALTER TABLE ONLY role
    ADD CONSTRAINT fk_role_on_person FOREIGN KEY (person_id) REFERENCES person(id);
