mutation createRole($filmId: Long!, $personId: Long!, $character: NonBlankString!) {
    createRole(roleInput: {filmId: $filmId, personId: $personId, character: $character}) {
        film {
            id
        }
        person {
            id
        }
        character
    }
}
