query role($filmId: Long!, $personId: Long!) {
    role(id: {filmId: $filmId, personId: $personId}) {
        film {
            id
        }
        person {
            id
        }
        character
    }
}
