mutation updateCast($filmId: Long!, $cast: [CastMemberInput!]) {
    updateCast(input: {filmId: $filmId, cast: $cast}) {
        cast {
            film {
                id
            }
            person {
                id
            }
            character
        }
    }
}
