mutation updateRole($filmId: Long!, $personId: Long!, $character: NonBlankString!) {
    updateRole(input: {id: {filmId: $filmId, personId: $personId}, character: $character}) {
        role {
            film { id }
            person { id }
            character
        }
    }
}
