mutation updateFilm($id: Long!, $title: NonBlankString!, $releaseDate: Date!, $synopsis: String) {
    updateFilm(input: {id: $id, filmInput: {title: $title, releaseDate: $releaseDate, synopsis: $synopsis}}) {
        film {
            id, title, releaseDate, synopsis
        }
    }
}
